# GPU 팬 제어 시스템 설정
fan_control:
  # 팬 경로 설정
  fans:
    gpu1: "/sys/class/hwmon/hwmon5/pwm7"      # 첫번째 GPU
    gpu2: "/sys/class/hwmon/hwmon5/pwm1"      # 두번째 GPU
    cpu: "/sys/class/hwmon/hwmon5/pwm2"       # CPU 수랭 쿨러 라디에이터 팬
    vrm: "/sys/class/hwmon/hwmon5/pwm6"       # 마더보드 VRM,칩셋 액티브 쿨링 통합 팬
  
  # 온도 임계점 설정
  temperature_thresholds:
    cpu:
      max_temp: 60    # CPU 온도 60도 이상 시 팬 100%
      min_temp: 40    # CPU 온도 40도 시 팬 50%
      min_speed: 50   # 최소 팬 속도 (%)
    
    gpu:
      critical_temp: 60  # GPU 60도 이상 시 모든 팬 최대
      min_temp: 40       # GPU 40도 시 해당 GPU 팬 0%
      max_temp: 60       # GPU 60도 시 해당 GPU 팬 100%
    
    vrm:
      cpu_temp_threshold: 50    # CPU 50도 이상 시 VRM 팬 100%
      gpu_temp_threshold: 50    # GPU 50도 이상 시 VRM 팬 100%
      default_speed: 50         # 기본 VRM 팬 속도 (%)
  
  # 전력 임계점 설정
  power_thresholds:
    gpu_critical_power: 100  # GPU 100W 이상 시 CPU 팬 최대
    vrm_activation_power: 80  # GPU 80W 이상 시 VRM 팬 100%
  
  # 제어 설정
  control:
    update_interval: 1  # 업데이트 주기 (초)
    pwm_max: 255       # PWM 최대값
    log_level: "DEBUG"  # 로그 레벨 (DEBUG, INFO, WARNING, ERROR) - 스무딩 디버깅용
    
    # 팬 속도 스무딩 설정
    smoothing:
      enabled: true          # 스무딩 활성화
      
      # CPU 팬
      cpu_max_change_up: 100   # CPU 팬 상승 시 최대 변화량 (% per second)
      cpu_max_change_down: 10 # CPU 팬 하강 시 최대 변화량 (% per second)
      
      # GPU 팬
      gpu_max_change_up: 10    # GPU 팬 상승 시 최대 변화량 (% per second)
      gpu_max_change_down: 5   # GPU 팬 하강 시 최대 변화량 (% per second)
      
      # VRM 팬
      vrm_max_change_up: 5    # VRM 팬 상승 시 최대 변화량 (% per second)
      vrm_max_change_down: 5   # VRM 팬 하강 시 최대 변화량 (% per second)
